
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ilknur
 */
public class MusteriDuzenleme extends javax.swing.JFrame {

    /**
     * Creates new form MusteriDuzenleme
     */
    public MusteriDuzenleme() {
        initComponents();
       
        this.setLocationRelativeTo(null);
        musterileri_tabloya_aktar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MusteriID = new javax.swing.JTextField();
        MAd = new javax.swing.JTextField();
        MSoyad = new javax.swing.JTextField();
        MTlf = new javax.swing.JTextField();
        MAdres = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablo = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Müşteri Düzenleme");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Müşteri ID:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Müşteri Adı:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Müşteri Soyadı:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Müşteri Telefon:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Müşteri Adres:");

        MusteriID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        MusteriID.setEnabled(false);
        MusteriID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusteriIDActionPerformed(evt);
            }
        });

        MAd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        MSoyad.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        MTlf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        MAdres.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Müşteri ID", "Müşteri Adı", "Müşteri Soyadı", "Müşteri Telefon", "Müşteri Adres"
            }
        ));
        tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablo);

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Müşteri Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Müşteri Sil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 0, 51));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("Bilgileri Güncelle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("Ana Ekrana Dön");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MAd, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(MusteriID, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(MAdres))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(MSoyad, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                .addComponent(MTlf))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButton4)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MusteriID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MAd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(MSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(MTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(MAdres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MusteriIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusteriIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MusteriIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          if(kontrolEt()){
           PreparedStatement st;
            ResultSet rs  ;
        String sorgu="INSERT INTO `musteri`( `MAd`, `MSoyad`, `MTlf`, `MAdres`) VALUES (?,?,?,?)";
           try{
               st=VeriTabaniBaglantisi.getConnection().prepareStatement(sorgu);
               
               st.setString(1, MAd.getText());
               st.setString(2, MSoyad.getText());
               st.setString(3, MTlf.getText());
               st.setString(4, MAdres.getText());
               st.executeUpdate();
             musterileri_tabloya_aktar();
               JOptionPane.showMessageDialog(null,"Müşteri Eklendi");
               MusteriID.setText("");
               MAd.setText("");
               MSoyad.setText("");
               MTlf.setText("");
               MAdres.setText("");
              
               
               
               
           }
           catch(Exception e){
               e.printStackTrace();
               
           }
       }else{
            JOptionPane.showMessageDialog(null,"Boş alan bırakılamaz");
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      PreparedStatement st;
        ResultSet rs  ;
        String sorgu="UPDATE musteri SET MAd=?, MSoyad=?,MTlf=?,MAdres=? WHERE MusteriID=?";
        try{
             st=VeriTabaniBaglantisi.getConnection().prepareStatement(sorgu);
               st.setString(1, MAd.getText());
               st.setString(2, MSoyad.getText());
               st.setString(3, MTlf.getText());
               st.setString(4, MAdres.getText());
               st.setInt(5,Integer.valueOf(MusteriID.getText()));
           st.executeUpdate();
          musterileri_tabloya_aktar();
           JOptionPane.showMessageDialog(null,"Müşteri Güncellendi");
               MusteriID.setText("");
               MAd.setText("");
               MSoyad.setText("");
               MTlf.setText("");
               MAdres.setText("");
             //  KitapDurum.setText("");
           
           
       }catch(Exception e){
           e.printStackTrace();
       } 
        
     
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(!MusteriID.equals("")){
        PreparedStatement st;
        ResultSet rs  ;
        String sorgu="DELETE FROM musteri WHERE MusteriID=?";
        try{
             st=VeriTabaniBaglantisi.getConnection().prepareStatement(sorgu);
             int MusteriId=Integer.parseInt(MusteriID.getText());
             st.setInt(1,MusteriId);
             st.executeUpdate();
             musterileri_tabloya_aktar();
              JOptionPane.showMessageDialog(null,"Müşteri Silindi");  
               MusteriID.setText("");
               MAd.setText("");
               MSoyad.setText("");
               MTlf.setText("");
               MAdres.setText("");
              // KitapDurum.setText("");
            }catch(Exception e){
                e.printStackTrace();
                
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Silinecek Müşteri Bulunamadı!"); 
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabloMouseClicked
        
        int index =tablo.getSelectedRow();
        try{
            MusteriGoster(index);
       
   }   catch(Exception e){
       
       
   }    
      
    }//GEN-LAST:event_tabloMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
       AnaEkran yAna=new AnaEkran();
                         setVisible(false);
                          yAna.setVisible(true);
        
    }//GEN-LAST:event_jButton4MouseClicked

     boolean kontrolEt(){
        if(MusteriID.getText()==null || MAd.getText()==null || MSoyad.getText()==null || MTlf.getText()==null || MAdres.getText()==null){
            return false;
        }
        else{
            return true;
        }
     }
     ArrayList<Sutunlar>getSutunlar(){
        ArrayList<Sutunlar>musteri_listesi=new ArrayList<>();
        PreparedStatement st;
       
        String sorguA="SELECT *FROM musteri";
        try{
           ResultSet rs  ;
           st=VeriTabaniBaglantisi.getConnection().prepareStatement(sorguA);
           rs=st.executeQuery(sorguA);
           Sutunlar s;
           while (rs.next()){
               s=new Sutunlar (rs.getInt("MusteriID"),rs.getString("MAd"),rs.getString("MSoyad"),rs.getInt("MTlf"),rs.getString("MAdres"));
               musteri_listesi.add(s);
           }
           
        }
        catch(Exception e){
            e.printStackTrace();
        }
        return musteri_listesi;
    }
    void musterileri_tabloya_aktar(){
        try{
            ArrayList<Sutunlar>list=getSutunlar();
            DefaultTableModel model=(DefaultTableModel)tablo.getModel();
            model.setRowCount(0);
          Object []satir=new Object[5];
          for(int i=0;i<list.size();i++){
              satir[0]=list.get(i).getMusteriID();
              satir[1]=list.get(i).getMAd();
              satir[2]=list.get(i).getMSoyad();
              satir[3]=list.get(i).getMTlf();
              satir[4]=list.get(i).getMAdres();
              
              model.addRow(satir);
          }
                  
            
        }catch(Exception e){
            e.printStackTrace();
            
        }
    }
    void MusteriGoster(int index){
        try{
            MusteriID.setText(Integer.toString(getSutunlar().get(index).getMusteriID()));
            MAd.setText(getSutunlar().get(index).getMAd());
            MSoyad.setText(getSutunlar().get(index).getMSoyad());
            MTlf.setText(Integer.toString(getSutunlar().get(index).getMTlf()));
            MAdres.setText(getSutunlar().get(index).getMAdres());
            
            
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }
     
     
     
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusteriDuzenleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusteriDuzenleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusteriDuzenleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusteriDuzenleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusteriDuzenleme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MAd;
    private javax.swing.JTextField MAdres;
    private javax.swing.JTextField MSoyad;
    private javax.swing.JTextField MTlf;
    private javax.swing.JTextField MusteriID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablo;
    // End of variables declaration//GEN-END:variables
}
